import { PATH } from '@/routes/path';

// 유저
export const MARKET_DETAIL = `${PATH.MARKET.BASE}/${PATH.MARKET.DETAIL.BASE}`;
export const ITEM_DETAIL = `${PATH.MARKET.BASE}/${PATH.MARKET.DETAIL.BASE}/${PATH.MARKET.DETAIL.ITEM.BASE}/${PATH.MARKET.DETAIL.ITEM.ITEM_ID}`;
export const SUPPORT_FAQ_DETAIL = `${PATH.MY.BASE}/${PATH.MY.SUPPORT.BASE}/${PATH.MY.SUPPORT.FAQ}`;

// 셀러
export const SELLER_ITEM_DETAIL = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}`;
export const SELLER_ITEM_EDIT_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.ITEM_ID.EDIT.BASE}`;
export const SELLER_ITEM_EDIT_INFO_TAB_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.ITEM_ID.EDIT.BASE}/${PATH.SELLER.ITEM.ITEM_ID.EDIT.TABS.INFO}`;
export const SELLER_ITEM_EDIT_FAQ_TAB_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.ITEM_ID.EDIT.BASE}/${PATH.SELLER.ITEM.ITEM_ID.EDIT.TABS.FAQ}`;
export const SELLER_ITEM_FAQ_REGISTER_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.FAQ.BASE}/${PATH.SELLER.ITEM.FAQ.REGISTRATION.BASE}`;
export const SELLER_ITEM_FAQ_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.FAQ.BASE}/${PATH.SELLER.ITEM.FAQ.FAQ_ID.BASE}`;
export const SELLER_ITEM_FAQ_EDIT_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.ITEM_ID.BASE}/${PATH.SELLER.ITEM.FAQ.BASE}/${PATH.SELLER.ITEM.FAQ.FAQ_ID.BASE}/${PATH.SELLER.ITEM.FAQ.FAQ_ID.FAQ_DETAIL.EDIT}`;
export const SELLER_SUPPORT_FAQ_DETAIL = `${PATH.SELLER.BASE}/${PATH.SELLER.MY.BASE}/${PATH.SELLER.MY.SETTING.BASE}/${PATH.SELLER.MY.SETTING.SUPPORT.BASE}/${PATH.SELLER.MY.SETTING.SUPPORT.FAQ}`;
export const SELLER_ITEM_REGISTRATION_PATH = `${PATH.SELLER.BASE}/${PATH.SELLER.ITEM.BASE}/${PATH.SELLER.ITEM.REGISTRATION.BASE}`;
