import { ItemCardType } from '@/types/common/ItemType.types';

export const itemMockData: ItemCardType[] = [
  {
    sellerProfileImg: '/profile.png',
    sellerUsername: 'user_one',
    sellerNickname: '유저원',
    sellerId: 1,
    itemId: 101,
    itemMainImg: '/product.png',
    itemPeriod: 7,
    itemName: '빈티지 가죽 가방',
    startDate: '2025-07-25T00:00:00.000Z',
    endDate: '2025-08-01T00:00:00.000Z',
    tagline: '한정 수량! 놓치지 마세요',
    currentStatus: 'DEFAULT',
    liked: true,
  },
  {
    sellerProfileImg: null,
    sellerUsername: 'seller_kim',
    sellerNickname: '김셀러',
    sellerId: 2,
    itemId: 102,
    itemMainImg: '/product.png',
    itemPeriod: 14,
    itemName: '모던 아트 포스터',
    startDate: '2025-07-25T00:00:00.000Z',
    endDate: '2025-08-01T00:00:00.000Z',
    tagline: null,
    currentStatus: 'EXTEND',
    liked: false,
  },
  {
    sellerProfileImg: '/profile3.png',
    sellerUsername: 'artlover33',
    sellerNickname: '아트러버',
    sellerId: 3,
    itemId: 103,
    itemMainImg: '/product.png',
    itemPeriod: 5,
    itemName: '수제 도자기 컵 세트',
    startDate: '2025-07-25T00:00:00.000Z',
    endDate: '2025-08-01T00:00:00.000Z',
    tagline: '따뜻한 감성을 담은 작품',
    currentStatus: 'SOLD_OUT',
    liked: true,
  },
];
